import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Bell, GraduationCap, ChevronRight, Zap, BarChart3, User, CheckCircle2, Share2, AlertTriangle, UserPlus, Wallet, Search, MessageCircle } from 'lucide-react';
import { format, isToday, isTomorrow, addHours, subDays } from 'date-fns';
import { cn } from '@/lib/utils';
import { ptBR } from 'date-fns/locale';

import { Link } from 'react-router-dom';
import { PersonalImpactReceipt } from '@/components/admin/PersonalImpactReceipt';
import { CheckinQueue } from '@/components/dashboard/CheckinQueue';
import { toLocalDateTime } from '@/lib/deadline';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

export function AdminDashboard() {
  const { user, profile } = useAuth();
  const [showImpact, setShowImpact] = useState(false);
  const [showRetention, setShowRetention] = useState(false);
  const [retentionDays, setRetentionDays] = useState<'7' | '15' | '30'>('7');
  const [retentionSearch, setRetentionSearch] = useState('');
  const today = format(new Date(), 'yyyy-MM-dd');

  const { data: pendingCount = 0 } = useQuery({
    queryKey: ['admin-stat-pending', user?.id],
    queryFn: async () => {
      // Get student IDs belonging to this admin
      const { data: students } = await supabase
        .from('profiles')
        .select('id')
        .eq('business_owner_id', user!.id)
        .eq('role', 'student');
      const studentIds = (students || []).map(s => s.id);
      if (studentIds.length === 0) return 0;
      const { data: appointments, error } = await supabase
        .from('appointments')
        .select('id, date, time_slot, notes')
        .eq('status', 'pending')
        .in('student_id', studentIds);
      if (error) throw error;
      if (!appointments) return 0;

      // Apply the same 72h visibility filter used by AdminRequests
      const QUEUE_VISIBILITY_HOURS = 72;
      const now = new Date();
      const visibilityDeadline = addHours(now, QUEUE_VISIBILITY_HOURS);
      const visible = appointments.filter((a) => {
        const isAutoGenerated = a.notes?.includes('Aluno Fixo');
        if (!isAutoGenerated) return true;
        const classTime = toLocalDateTime(a.date, a.time_slot);
        return classTime <= visibilityDeadline;
      });
      return visible.length;
    },
    enabled: !!user?.id,
  });

  const { data: studentCount = 0 } = useQuery({
    queryKey: ['admin-stat-students'],
    queryFn: async () => {
      const { count, error } = await supabase
        .from('profiles')
        .select('*', { count: 'exact', head: true })
        .eq('role', 'student')
        .eq('business_owner_id', user!.id);
      if (error) throw error;
      return count ?? 0;
    },
    enabled: !!user?.id,
  });

  const { data: collaboratorCount = 0 } = useQuery({
    queryKey: ['admin-stat-collaborators', user?.id],
    queryFn: async () => {
      const { count, error } = await supabase
        .from('profiles')
        .select('*', { count: 'exact', head: true })
        .eq('role', 'collaborator')
        .eq('business_owner_id', user!.id)
        .eq('is_active', true);
      if (error) throw error;
      return count ?? 0;
    },
    enabled: !!user?.id,
  });

  const { data: nextAppointment } = useQuery({
    queryKey: ['admin-next-appointment', user?.id],
    queryFn: async () => {
      // Fetch upcoming confirmed appointments for the entire studio
      const { data: appts, error } = await supabase
        .from('appointments')
        .select('id, date, time_slot, status, student_id, instructor_id')
        .in('status', ['confirmed', 'delegated'])
        .gte('date', today)
        .order('date')
        .order('time_slot')
        .limit(20);
      if (error) throw error;
      if (!appts || appts.length === 0) return null;

      // Filter to only future appointments (date+time > now)
      const now = new Date();
      const future = appts.filter((a) => toLocalDateTime(a.date, a.time_slot) > now);
      if (future.length === 0) return null;

      const appt = future[0];

      // Fetch student name
      const { data: studentProfile } = await supabase
        .from('profiles')
        .select('name')
        .eq('id', appt.student_id)
        .single();

      // Fetch instructor name if different from admin
      let instructorLabel = 'Você (Admin)';
      if (appt.instructor_id && appt.instructor_id !== user!.id) {
        const { data: instrProfile } = await supabase
          .from('profiles')
          .select('name')
          .eq('id', appt.instructor_id)
          .single();
        instructorLabel = instrProfile?.name || 'Colaborador';
      }

      const apptDate = new Date(appt.date + 'T00:00:00');
      let dateLabel: string;
      if (isToday(apptDate)) {
        dateLabel = 'Hoje';
      } else if (isTomorrow(apptDate)) {
        dateLabel = 'Amanhã';
      } else {
        dateLabel = format(apptDate, "EEEE, d 'de' MMM", { locale: ptBR });
      }

      return {
        dateLabel,
        time: appt.time_slot,
        studentName: studentProfile?.name || 'Aluno',
        instructorLabel,
      };
    },
    enabled: !!user?.id,
    refetchInterval: 60_000,
  });

  const todayFormatted = format(new Date(), "EEEE, d 'de' MMMM", { locale: ptBR });

  const { data: inactiveCount = 0 } = useQuery({
    queryKey: ['admin-inactive-students', user?.id],
    queryFn: async () => {
      const { data: students } = await supabase
        .from('profiles')
        .select('id')
        .eq('business_owner_id', user!.id)
        .eq('role', 'student');
      const ids = (students || []).map((s) => s.id);
      if (ids.length === 0) return 0;
      const cutoff = format(subDays(new Date(), 7), 'yyyy-MM-dd');
      const { data: recent } = await supabase
        .from('appointments')
        .select('student_id')
        .in('student_id', ids)
        .gte('date', cutoff);
      const activeIds = new Set((recent || []).map((a) => a.student_id));
      return ids.filter((id) => !activeIds.has(id)).length;
    },
    enabled: !!user?.id,
  });

  const { data: inactiveStudents = [] } = useQuery({
    queryKey: ['admin-inactive-students-list', user?.id, retentionDays],
    queryFn: async () => {
      const { data: students } = await supabase
        .from('profiles')
        .select('id, name, phone, photo_url')
        .eq('business_owner_id', user!.id)
        .eq('role', 'student');
      const list = students || [];
      if (list.length === 0) return [];
      const cutoff = format(subDays(new Date(), Number(retentionDays)), 'yyyy-MM-dd');
      const ids = list.map((s) => s.id);
      const { data: recent } = await supabase
        .from('appointments')
        .select('student_id')
        .in('student_id', ids)
        .gte('date', cutoff);
      const activeIds = new Set((recent || []).map((a) => a.student_id));
      return list.filter((s) => !activeIds.has(s.id));
    },
    enabled: !!user?.id && showRetention,
  });

  const filteredInactive = inactiveStudents.filter((s) =>
    (s.name || '').toLowerCase().includes(retentionSearch.toLowerCase())
  );

  return (
    <div className="flex flex-col gap-4 animate-fade-in max-w-full overflow-hidden pb-24">
      <div className="space-y-1 mb-2">
        <h1 className="text-2xl font-bold text-slate-900">
          Olá, {(() => {
            const raw = profile?.name?.split(' ')[0] || 'Igor';
            return raw.charAt(0).toUpperCase() + raw.slice(1).toLowerCase();
          })()}! 👋
        </h1>
        <p className="text-sm text-slate-500 capitalize">{todayFormatted}</p>
      </div>

      {/* Check-in Validation Queue */}
      <CheckinQueue />

      {/* Próximo Agendamento (Priority #1) */}
      <Card className="bg-white border border-slate-100 shadow-sm rounded-2xl">
        <CardContent className="p-5">
          {nextAppointment ? (
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 rounded-xl bg-orange-50 flex items-center justify-center shrink-0">
                <Zap className="w-5 h-5 text-orange-500" />
              </div>
              <div className="flex-1 min-w-0 space-y-1">
                <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Próximo Agendamento</p>
                <p className="text-base font-bold text-slate-900">
                  {nextAppointment.dateLabel}, {nextAppointment.time}
                </p>
                <div className="flex flex-col gap-0.5">
                  <p className="text-sm text-muted-foreground flex items-center gap-1.5">
                    <User className="w-3.5 h-3.5 shrink-0" />
                    Aluno: {nextAppointment.studentName}
                  </p>
                  <p className="text-sm text-muted-foreground flex items-center gap-1.5">
                    <GraduationCap className="w-3.5 h-3.5 shrink-0" />
                    Professor: {nextAppointment.instructorLabel}
                  </p>
                </div>
              </div>
            </div>
          ) : (
            <div className="flex items-center gap-4">
              <div className="w-10 h-10 rounded-xl bg-orange-50 flex items-center justify-center shrink-0">
                <Zap className="w-5 h-5 text-orange-500" />
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-bold text-slate-900">Sem mais treinos agendados!</p>
                <p className="text-xs text-muted-foreground">Dia de descanso! 💪</p>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Solicitações Pendentes — smart empty state */}
      {pendingCount > 0 ? (
        <Link to="/dashboard/solicitacoes">
          <Card className="bg-white border border-slate-100 shadow-sm rounded-2xl border-l-4 border-l-orange-500 hover:shadow-md transition-shadow cursor-pointer active:scale-[0.98]">
            <CardContent className="p-5 flex items-center gap-4">
              <div className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0 bg-orange-50">
                <Bell className="w-5 h-5 text-orange-500" />
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-bold text-slate-900">
                  {pendingCount} Solicitações Pendentes
                </p>
                <p className="text-xs text-slate-500">Toque para revisar</p>
              </div>
              <ChevronRight className="w-4 h-4 text-slate-400 shrink-0" />
            </CardContent>
          </Card>
        </Link>
      ) : (
        <div className="bg-white border border-slate-100 shadow-sm rounded-2xl p-4 flex items-center justify-center gap-2 text-sm font-medium text-emerald-600">
          <CheckCircle2 className="w-4 h-4" />
          Tudo em dia! Sem pendências.
        </div>
      )}

      {/* Resumo da Semana — minimalist strip */}
      <button
        type="button"
        onClick={() => setShowImpact(true)}
        className="w-full flex items-center justify-between p-5 rounded-2xl bg-white border border-slate-100 shadow-sm hover:shadow-md transition-all active:scale-[0.99]"
      >
        <div className="flex items-center gap-3 min-w-0">
          <div className="w-10 h-10 rounded-xl bg-orange-50 flex items-center justify-center shrink-0">
            <BarChart3 className="w-5 h-5 text-orange-500" />
          </div>
          <div className="text-left min-w-0">
            <p className="text-sm font-semibold text-slate-900 truncate">Resumo da Semana</p>
            <p className="text-xs text-slate-500 truncate">Compartilhe no Instagram</p>
          </div>
        </div>
        <span className="w-8 h-8 rounded-full border border-orange-200 text-orange-500 flex items-center justify-center shrink-0">
          <Share2 className="w-4 h-4" />
        </span>
      </button>

      {showImpact && <PersonalImpactReceipt open={showImpact} onOpenChange={setShowImpact} />}

      {/* Radar de Retenção */}
      <Card className={cn(
        'bg-white border border-slate-100 shadow-sm rounded-2xl',
        inactiveCount > 0 && 'border-l-4 border-l-rose-500'
      )}>
        <CardContent className="p-5 flex items-center gap-4">
          <div className={cn(
            'w-10 h-10 rounded-xl flex items-center justify-center shrink-0',
            inactiveCount > 0 ? 'bg-rose-50 text-rose-500' : 'bg-emerald-50 text-emerald-500'
          )}>
            <AlertTriangle className="w-5 h-5" />
          </div>
          <div className="flex-1 min-w-0">
            <p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Radar de Retenção</p>
            {inactiveCount > 0 ? (
              <p className="text-sm font-bold text-rose-600">
                {inactiveCount} {inactiveCount === 1 ? 'aluno inativo' : 'alunos inativos'} há mais de 7 dias
              </p>
            ) : (
              <p className="text-sm font-bold text-emerald-600">
                Todos os alunos ativos esta semana 🎯
              </p>
            )}
          </div>
          {inactiveCount > 0 && (
            <Button
              size="sm"
              variant="outline"
              onClick={() => setShowRetention(true)}
              className="border border-orange-200 text-orange-600 bg-transparent rounded-xl hover:bg-orange-50 shrink-0"
            >
              Ver Alunos
            </Button>
          )}
        </CardContent>
      </Card>

      {/* Ações Rápidas */}
      <div className="grid grid-cols-2 gap-3">
        <Link
          to="/dashboard/meus-alunos"
          className="inline-flex items-center justify-center gap-2 bg-orange-500 hover:bg-orange-600 text-white font-semibold rounded-xl py-3 px-4 transition-all active:scale-[0.99]"
        >
          <UserPlus className="w-4 h-4" />
          Novo Aluno
        </Link>
        <Link
          to="/dashboard/admin/financeiro"
          className="inline-flex items-center justify-center gap-2 border border-orange-200 text-orange-600 bg-transparent hover:bg-orange-50 font-semibold rounded-xl py-3 px-4 transition-all active:scale-[0.99]"
        >
          <Wallet className="w-4 h-4" />
          Financeiro
        </Link>
      </div>

      {/* Painel de Retenção */}
      <Sheet open={showRetention} onOpenChange={setShowRetention}>
        <SheetContent side="right" className="w-full sm:max-w-md overflow-y-auto">
          <SheetHeader>
            <SheetTitle className="flex items-center gap-2">
              <AlertTriangle className="w-5 h-5 text-rose-500" />
              Painel de Retenção
            </SheetTitle>
            <SheetDescription>
              Identifique e recupere alunos inativos rapidamente.
            </SheetDescription>
          </SheetHeader>

          <div className="mt-4 space-y-3">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input
                placeholder="Buscar aluno..."
                value={retentionSearch}
                onChange={(e) => setRetentionSearch(e.target.value)}
                className="pl-9"
              />
            </div>
            <Select value={retentionDays} onValueChange={(v) => setRetentionDays(v as '7' | '15' | '30')}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="7">Inativos há 7 dias</SelectItem>
                <SelectItem value="15">Inativos há 15 dias</SelectItem>
                <SelectItem value="30">Inativos há 30 dias</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="mt-4 space-y-2">
            {filteredInactive.length === 0 ? (
              <div className="py-12 text-center text-sm text-muted-foreground">
                Nenhum aluno inativo neste período 🎯
              </div>
            ) : (
              filteredInactive.map((s) => {
                const cleanPhone = (s.phone || '').replace(/\D/g, '');
                const waUrl = cleanPhone ? `https://wa.me/55${cleanPhone}` : null;
                return (
                  <div
                    key={s.id}
                    className="flex items-center gap-3 p-3 rounded-2xl border border-border bg-card"
                  >
                    {s.photo_url ? (
                      <img src={s.photo_url} alt="" className="w-10 h-10 rounded-full object-cover" />
                    ) : (
                      <div className="w-10 h-10 rounded-full bg-muted flex items-center justify-center">
                        <User className="w-5 h-5 text-muted-foreground" />
                      </div>
                    )}
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-semibold truncate">{s.name}</p>
                      <p className="text-xs text-muted-foreground truncate">
                        {s.phone || 'Sem telefone'}
                      </p>
                    </div>
                    {waUrl && (
                      <a
                        href={waUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="w-9 h-9 rounded-full bg-emerald-500 hover:bg-emerald-600 text-white flex items-center justify-center shrink-0"
                        aria-label="WhatsApp"
                      >
                        <MessageCircle className="w-4 h-4" />
                      </a>
                    )}
                  </div>
                );
              })
            )}
          </div>
        </SheetContent>
      </Sheet>
    </div>
  );
}


